---
title: ProtoMED, MUN Biomedical Engineering
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: MUN ProtoMED is a biomedical engineering team focused on rapid prototyping,
  especially 3D printing.
url: http://protomed.ca
username: MUN ProtoMED
user_description: 
user_title: MUN Biomedical Engineering Team
google-analytics:
  id: ''
exclude:
- package.json
- src
- node_modules
